apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-pod-netpol
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: secure-pod
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: webapp-color
