apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: messaging-service
  namespace: marketing
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-pod
status:
  loadBalancer: {}
