apiVersion: batch/v1beta1
kind: CronJob
metadata:       
  name: dice
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 20
      completions: 1
      backoffLimit: 25
      template:
        spec:
          containers:
          - image: kodekloud/throw-dice
            name: throw-dice
          restartPolicy: Never
