apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-busybox
  name: my-busybox
  namespace: dev2406
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret
  containers:
  - image: busybox
    name: secret
    command:
    - "sleep"
    - "3600"
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
      readOnly: true
  tolerations: # the secheduling on the control plane can be done using the spec.nodeName field
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
